# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Haverford_Form' do
pod 'Google/SignIn'
pod 'Parse'
pod 'BFPaperButton', '~> 2.0.18'
pod 'PayPal-iOS-SDK'
pod 'mailcore2-ios'
end

target 'Haverford_FormTests' do

end

